Naam = input("Vul hier je naam in: ")
Adres = input("Vul hier je adres in: ")
Postcode = input("Vul hier je postcode in: ")
Woonplaats = input("Vul hier je woonplaats in: ")

print(" ----------------------------------------------------")
print("|  Naam      : " + Naam)
print("|  Adres     : " + Adres)
print("|  Postcode  : " + Postcode)
print("|  Woonplaats: " + Woonplaats)
print(" ----------------------------------------------------")